export default [
    {
        label: '进入',
        children: [
            { label: '渐显',status:false, value: 'fadeIn' },
            { label: '向右进入',status:false, value: 'fadeInLeft' },
            { label: '向左进入',status:false, value: 'fadeInRight' },
            { label: '向上进入',status:false, value: 'fadeInUp' },
            { label: '向下进入',status:false, value: 'fadeInDown' },
            { label: '向右长距进入',status:false, value: 'fadeInLeftBig' },
            { label: '向左长距进入',status:false, value: 'fadeInRightBig' },
            { label: '向上长距进入',status:false, value: 'fadeInUpBig' },
            { label: '向下长距进入',status:false, value: 'fadeInDownBig' },
            { label: '旋转进入',status:false, value: 'rotateIn' },
            { label: '左顺时针旋转',status:false, value: 'rotateInDownLeft' },
            { label: '右逆时针旋转',status:false, value: 'rotateInDownRight' },
            { label: '左逆时针旋转',status:false, value: 'rotateInUpLeft' },
            { label: '右逆时针旋转',status:false, value: 'rotateInUpRight' },
            { label: '弹入',status:false, value: 'bounceIn' },
            { label: '向右弹入',status:false, value: 'bounceInLeft' },
            { label: '向左弹入',status:false, value: 'bounceInRight' },
            { label: '向上弹入',status:false, value: 'bounceInUp' },
            { label: '向下弹入',status:false, value: 'bounceInDown' },
            { label: '光速从右进入',status:false, value: 'lightSpeedInRight' },
            { label: '光速从左进入',status:false, value: 'lightSpeedInLeft' },
            { label: '光速从右退出',status:false, value: 'lightSpeedOutRight' },
            { label: '光速从左退出',status:false, value: 'lightSpeedOutLeft' },
            { label: 'Y轴旋转',status:false, value: 'flip' },
            { label: '中心X轴旋转',status:false, value: 'flipInX' },
            { label: '中心Y轴旋转',status:false, value: 'flipInY' },
            { label: '左长半径旋转',status:false, value: 'rollIn' },
            { label: '由小变大进入',status:false, value: 'zoomIn' },
            { label: '左变大进入',status:false, value: 'zoomInLeft' },
            { label: '右变大进入',status:false, value: 'zoomInRight' },
            { label: '向上变大进入',status:false, value: 'zoomInUp' },
            { label: '向下变大进入',status:false, value: 'zoomInDown' },
            { label: '向右滑动展开',status:false, value: 'slideInLeft' },
            { label: '向左滑动展开',status:false, value: 'slideInRight' },
            { label: '向上滑动展开',status:false, value: 'slideInUp' },
            { label: '向下滑动展开',status:false, value: 'slideInDown' },
        ],
    },
    {
        label: '强调',
        children: [
            { label: '弹跳',status:false, value: 'bounce' },
            { label: '闪烁',status:false, value: 'flash' },
            { label: '放大缩小',status:false, value: 'pulse' },
            { label: '放大缩小弹簧',status:false, value: 'rubberBand' },
            { label: '左右晃动',status:false, value: 'headShake' },
            { label: '左右扇形摇摆',status:false, value: 'swing' },
            { label: '放大晃动缩小',status:false, value: 'tada' },
            { label: '扇形摇摆',status:false, value: 'wobble' },
            { label: '左右上下晃动',status:false, value: 'jello' },
            { label: 'Y轴旋转',status:false, value: 'flip' },
        ],
    },
    {
        label: '退出',
        children: [
            { label: '渐隐',status:false, value: 'fadeOut' },
            { label: '向左退出',status:false, value: 'fadeOutLeft' },
            { label: '向右退出',status:false, value: 'fadeOutRight' },
            { label: '向上退出',status:false, value: 'fadeOutUp' },
            { label: '向下退出',status:false, value: 'fadeOutDown' },
            { label: '向左长距退出',status:false, value: 'fadeOutLeftBig' },
            { label: '向右长距退出',status:false, value: 'fadeOutRightBig' },
            { label: '向上长距退出',status:false, value: 'fadeOutUpBig' },
            { label: '向下长距退出',status:false, value: 'fadeOutDownBig' },
            { label: '旋转退出',status:false, value: 'rotateOut' },
            { label: '左顺时针旋转',status:false, value: 'rotateOutDownLeft' },
            { label: '右逆时针旋转',status:false, value: 'rotateOutDownRight' },
            { label: '左逆时针旋转',status:false, value: 'rotateOutUpLeft' },
            { label: '右逆时针旋转',status:false, value: 'rotateOutUpRight' },
            { label: '弹出',status:false, value: 'bounceOut' },
            { label: '向左弹出',status:false, value: 'bounceOutLeft' },
            { label: '向右弹出',status:false, value: 'bounceOutRight' },
            { label: '向上弹出',status:false, value: 'bounceOutUp' },
            { label: '向下弹出',status:false, value: 'bounceOutDown' },
            { label: '中心X轴旋转',status:false, value: 'flipOutX' },
            { label: '中心Y轴旋转',status:false, value: 'flipOutY' },
            { label: '左长半径旋转',status:false, value: 'rollOut' },
            { label: '由小变大退出',status:false, value: 'zoomOut' },
            { label: '左变大退出',status:false, value: 'zoomOutLeft' },
            { label: '右变大退出',status:false, value: 'zoomOutRight' },
            { label: '向上变大退出',status:false, value: 'zoomOutUp' },
            { label: '向下变大退出',status:false, value: 'zoomOutDown' },
            { label: '向左滑动收起',status:false, value: 'slideOutLeft' },
            { label: '向右滑动收起',status:false, value: 'slideOutRight' },
            { label: '向上滑动收起',status:false, value: 'slideOutUp' },
            { label: '向下滑动收起',status:false, value: 'slideOutDown' },
        ],
    },
]
